# Generated by Django 3.1.7 on 2021-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ein',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
