# Generated by Django 3.1.7 on 2021-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210222_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ein',
            field=models.IntegerField(),
        ),
    ]
